spring.application.name=WebCrawler

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

server.port=8081

crawler.storage.output-dir=${CRAWLER_STORAGE_OUTPUT_DIR:C:/WebCrawler/crawled-pages}