spring.application.name=WebCrawler

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

huggingface.api.token=${HUGGINGFACE_API_TOKEN}
elasticsearch.host=${ELASTICSEARCH_HOST:http://localhost:9200}